Cập nhật mô hình cài đặt theo
vietstacker/OpenStack-Newton-Scripts pull request #7
Opened 2016-11-16 04:25 UTC by congto

2016-11-16 04:27 UTC, congto commented
@hieulq check tài liệu nhé. Update tài liệu theo docs, anh và @thaihust contribute

2016-11-16 09:18 UTC, hieulq commented on OPS-U16/scripts/setup02.sh
> +	echocolor "Install MYSQL"
this should be MariaDB, right?

2016-11-16 09:18 UTC, hieulq commented on OPS-U16/scripts/setup01.sh
> +        echocolor  "Thu thi voi cac tuy chon sau"
what dis this mean? "Thú thí"?

2016-11-16 09:29 UTC, hieulq commented
@congto @thaihust please check my comments in previous PR.
How about writing all comments and console output in English?

2016-11-16 09:30 UTC, hieulq requested changes
-1

2016-11-16 09:39 UTC, hieulq commented
@thaihust @congto I will turn-on the CI job for checking bashate and shellcheck. This mean all your PR must pass the CI job before merging.
Have fun! ;)

2016-11-16 09:53 UTC, congto commented on OPS-U16/scripts/setup01.sh
> +        echocolor  "Thu thi voi cac tuy chon sau"
@hieulq Tha thu , It is "THA THU".

2016-11-16 09:55 UTC, congto commented
@hieulq tài liệu viết theo docs và cài manual  thì chơi bằng tiếng Việt đi, script thì mới chơi ENG, Tiếng ENG có rồi viết lại làm gì.

2016-11-16 10:02 UTC, hieulq commented
@congto đọc kỹ trước khi ý kiến, em đang nói viết script bằng tiếng anh hay viết doc bằng tiếng anh?
Re-quote: "How about writing all comments and console output in English?"

2016-11-16 10:03 UTC, hieulq commented
@congto @thaihust will turn-on the CI later after my trip (next week).

2016-11-16 10:41 UTC, congto commented
@hieulq 
- docs cài đặt step by step = tiếng Việt.
- Comment và các output trong script = ENG. E là người chuyển từ VIE sang ENG nhé 👍

2016-11-16 11:01 UTC, hieulq commented
@congto

không, làm đi cho nó tiến bộ

On Wed, Nov 16, 2016 at 17:41 Tô Thành Công <notifications@github.com>
wrote:

> @hieulq <https://github.com/hieulq>
>
>    - docs cài đặt step by step = tiếng Việt.
>    - Comment và các output trong script = ENG. E là người chuyển từ VIE
>    sang ENG nhé 👍
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/vietstacker/OpenStack-Newton-Scripts/pull/7#issuecomment-260913196>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABui7n9LY7Hjj1LrvGmbFB3RjDLAOK_Oks5q-t32gaJpZM4KzWlv>
> .
>

2016-11-16 12:34 UTC, congto commented
@hieulq mệt lắm

2016-11-16 13:24 UTC, hieulq commented
@congto thế thôi khỏi merge

On Wed, Nov 16, 2016 at 19:34 Tô Thành Công <notifications@github.com>
wrote:

> @hieulq <https://github.com/hieulq> mệt lắm
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/vietstacker/OpenStack-Newton-Scripts/pull/7#issuecomment-260935562>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABui7qeniXjqMbrNlIKJBQ_tpNRQ3Exiks5q-vhUgaJpZM4KzWlv>
> .
>

2016-11-17 07:35 UTC, hieulq commented
@congto @thaihust CI is now enable, if your PR do not pass the CI for bashate (codestyle, whitespace..), the code will never be merged in the master branch.
Have fun! ;)

2016-11-17 08:28 UTC, congto commented
@hieulq Em kiểm tra lại chô CI, với bài của @thaihust  thì viết theo kiểu manual thì cũng check hay ntn ?

2016-11-17 08:47 UTC, hieulq commented
@congto chỉ check bash shell

On Thu, Nov 17, 2016 at 17:28 Tô Thành Công <notifications@github.com>
wrote:

> @hieulq <https://github.com/hieulq> Em kiểm tra lại chô CI, với bài của
> @thaihust <https://github.com/thaihust> thì viết theo kiểu manual thì
> cũng check hay ntn ?
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/vietstacker/OpenStack-Newton-Scripts/pull/7#issuecomment-261185286>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABui7mCMchTi9uXUpa7Sb2MU0DlpFoCqks5q_BA-gaJpZM4KzWlv>
> .
>

2016-11-18 01:35 UTC, hieulq commented
@congto @thaihust due to the fucking discussion today, I will remove the bashate CI and no longer join any activities like that from now.
Have fun.

2016-11-18 01:40 UTC, congto commented
@hieulq 🎱

2016-11-18 01:40 UTC, closed without merging